variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA #unix id

stages:
  - build
  - deploy_to_production

build:
  stage: build
  image: docker:latest
  variables:
    # using "docker" as the host is only possible if you alias the service below
    DOCKER_HOST: tcp://docker:2375
    # could be wrong here but although Docker defaults to overlay2,
    # Docker-in-Docker (DIND) does not according to the following GitLab doc:
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-overlayfs-driver
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    # - docker:dind #docker in docker
    - name: docker:dind
      alias: docker
      command: [ "--tls=false" ]
  only:
    - /^live_[0-9]+(?:.[0-9]+)+$/ # regular expression live_0.0.1, live_0.0.2, live_0.0.3, etc.
  script:
    - pwd
    - ls /home
    - echo "current user-> $USER"
    - docker build -t $TAG_COMMIT . #build docker image từ mã nguồn
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY #login vào docker registry
    - docker push $TAG_COMMIT #push docker image lên registry

deploy:
  stage: deploy_to_production
  image: alpine:latest #linux
  tags:
    - html
  only:
    - /^live_[0-9]+(?:.[0-9]+)+$/ # regular expression live_0.0.1, live_0.0.2, live_0.0.3, etc.
  script:
    - echo "Deploy to production"
    - echo $SERVER_USER
    - echo $GITLAB_CI_SSH_KEY
    - chmod 600 $GITLAB_CI_SSH_KEY
    - apk update && apk add openssh-client #cài đặt package openssh-client
    - ssh -o StrictHostKeyChecking=no -i $GITLAB_CI_SSH_KEY $SERVER_USER@$SERVER_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY" #login vào registry
    - ssh -o StrictHostKeyChecking=no -i $GITLAB_CI_SSH_KEY $SERVER_USER@$SERVER_HOST "docker pull $TAG_COMMIT" #pull docker image về server
    - ssh -o StrictHostKeyChecking=no -i $GITLAB_CI_SSH_KEY $SERVER_USER@$SERVER_HOST "docker container rm -f html-app || true" #xoá ảnh cũ có tên là html-app đi
    - ssh -o StrictHostKeyChecking=no -i $GITLAB_CI_SSH_KEY $SERVER_USER@$SERVER_HOST "docker run -d --name html-app -p 80:80 $TAG_COMMIT" #run docker image với tên là html-app
  environment:
    name: production
    url: http://$SERVER_HOST #url của server chạy web